language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "c8+GeM1D3J10jg20ZTabx4JqjZCn51eE+NR93WR0vPdPUCUq64q93DSg7F42rSS1nnWua832BuGbZx1oh0oFXwerf27bZl/b+X8AqYlXtXcBG3FlJKz2CSM6g8LGGOeqhPc2GCSKVta3ftAOUlw1UAAbkmlwuXsn2evijwOAAwIkCnyl2gu0mWcisURBWnvcck5Z7WLfZUE7mhPjamG00cOJbY06g5zLIVgoaIXnLMD2cs49/APxGwK6C9RrU64Sf9KjHP7pVn5hSzNxi3OXEydFvTC8ux8IXK9in7Q8aYumdyZpGj2d0AzLvfmGqyWAxCDsYwdKg7dBKK6khg9V+eckWrFPGEnbfZlx914lwc4MqdVd5f3F7kMCeubUPUlsLzm1AW3C+w5HmVPWS7TUo3Ibg4xjv3dj0U7j+mqJB23w/6vOEfZ62CL8RQHK+QfUpQwLrNnIHEIUd8yx+eXtW1AZnPGa266PFH0agif1hbu9juX9IS3rj5/EiYZKIUqt8QJjRNngAGZRuBWrvR+6WGw2X4bvewYTuaoTqDIihv+XDSVPxgP6Q1BCB9EQ+xLwrWlqyBiomB64iyyPw0GyRtBfGJoUXTZBdGjk9M3Ns7QDbwzKkaN9WYFA1RrHxoELEUYjmGcL7n9g271O5OqUFE2IVjDykcfv+92m4gjhK7Y="
  api_key: # 67b2
    secure: "evqfdCuylVRsRNJFY7rMjC9cY3PUtPXO21rg7mSnmSmjBkX+Smq0hiR8UwEfPnK5QkwvhOAL3B3KaCfbmmjLXRC00Av8hVbQgywm35uxaMIPqqBPbvj+Y+sHIEMuVGhnBzTXbfy63BqdpSEa6qAlsw/xXc2ei8w6LC6SsdakGKV90GCNtadAibzZ3lBH2qgP5ibl97aq53PnDrE/96/m2oEulxe2xoSLAFSqoxmE+ZiXy8LQo8snLhqUbcu79WarJ3qL+wY1U3buBnabbDpzaXUEWXVNU9npJCWqIgl4Y32cg/57Dk+TLy5bOj50vlm/5oWVCRFEexDnjbaTN/zhSFOdoj0SBGyIbwr95WV4EASegezRjwSX5XotxeuLkeGVV6YbI3uVysqbsqTGtT/UWlXkM2bgWqZ6iJpL0kFNG+1Mj2jcidyfTVXVmTLQYcxnqNEKq2oCvj4TIbw+B3+EMMGMVeYjaU6ok+4josldB4mPso/K0x/H2ZNwVJcj+ZEbTPmYRHrbCsJjoAH8I04IltTImik4yiltHqplZHtAkg3vicps0LjRwvh763WAvpaympzFsAIL7g3Fe7iMaj5ocyPXBxB3U4hQG3gURb//coF/SQJXGc05MJPSHX6GQreHtcZqAl7tgxf/R/SRcTRK0ttWuUSOg4BVWwuEy40f2aI="
  on:
    tags: true
    node: lts/*
